### ISSUE TITLE
Fullscreen controls

### ISSUE THREAD

**Issue by ram02z** [howardchung/watchparty#47]
When you go fullscreen, you lose the ability to use any of the video player's controls. Being able to pause, skip forward and change the volume whilst fullscreen would be very useful.

**Comment by howardchung** [comment]
I think to do this effectively we'll need to float the custom controls over the video and display them when the mouse is at the bottom of the screen.

**Comment by howardchung** [comment]
Hi, this is somewhat resolved with https://github.com/howardchung/watchparty/issues/134 which allows the keyboard controls to work even in fullscreen mode.

If you want an actual UI with buttons and icons etc. we can keep the issue open, but otherwise feel free to close if that resolves the problem for you.
